### ISSUE TITLE
Remove FS reference for Web Browser JavaScript Support

### ISSUE THREAD

**Issue by benjamin-stern** [2Toad/Profanity#17]
When trying to compile you package with our web module the following error is output:

`ERROR in ./node_modules/@2toad/profanity/dist/list.js
Module not found: Error: Can't resolve 'fs' in 'C:\LocalProjects\DrawAlive_Web_Product\Server\Server\node_modules\@2toad\profanity\dist'
 @ ./node_modules/@2toad/profanity/dist/list.js 4:13-26
 @ ./node_modules/@2toad/profanity/dist/profanity.js
 @ ./node_modules/@2toad/profanity/dist/index.js` 

Would prefer an alternative to the FS call.

**Comment by JasonPierce** [comment]
I don't believe there is an equivalent way to load files from within a Browser (security prevents this). We'd have to embed the contents of words.txt within the source itself -- which, isn't necessarily a bad idea, since we don't actually update the words.txt file very often. We could place it inside of a JavaScript file instead, and just import it. That would remove the need for `fs` or any file reading requirements.
