### ISSUE TITLE
Combine Google's profanity word list with existing word list

### ISSUE THREAD

**Issue by bjbarouch** [2Toad/Profanity#43]
The attached file is a merge of the data found here and something claimed to be google's list. The next result is just over a thousand entries instead of fewer than 500. More is not better if too many false positive result, but I think this larger file is good. Changed from .ts to .txt just to upload it.
[profane-words.txt](https://github.com/2Toad/Profanity/files/11901592/profane-words.txt)

**Comment by jzombie** [comment]
I added a PR here: https://github.com/2Toad/Profanity/pull/44

And created a fork here w/ this already merged in: https://github.com/zenOSmosis/profanity-filter-ts

**Comment by bjbarouch** [comment]
And I see it is already closed. Thanks, and thanks for the project.

**Comment by JasonPierce** [comment]
@bjbarouch not sure what happened with this issue and who closed the related PR, but it looks like the referenced fork is no longer available. Is there still a desire to merge this in?

**Comment by jzombie** [comment]
@JasonPierce , it was me who closed it, inadvertently.  I moved the org that the repo was under to my personal account.

I think if I were to do this all over again, though, I'd not hardcode all these strings in, but use linear algebra performed against ML-generated embeddings.

**Comment by JasonPierce** [comment]
I've created a branch to implement this, [jp-issue-43](https://github.com/2Toad/Profanity/tree/jp-issue-43), but am keeping it open because I'm undecided about expanding the current word list. Adding more words is beneficial for catching additional profanity (🧼). However, merging the "Google" list with the existing one more than doubles the number of profane words, which predictably impacts performance:

Performance Decreases
```
exists() - small clean text: -0.58%
exists() - small profane text: -8.79%
exists() - large clean text: -4.77%
censor() - Word, small profane text: -8.10%
censor() - FirstChar, small profane text: -1.07%
censor() - FirstVowel, small profane text: -8.98%
censor() - AllVowels, small profane text: -4.49%
censor() - Word, large profane text: -2.94%
censor() - partial match, Word, small profane text: -25.75%
```

Performance Increases
```
exists() - large profane text: +2.83%
exists() - partial match, small profane text: +119.06%
```

Why are we seeing a performance improvement in two of the scenarios? I'm not entirely certain, but the performance improvements are likely due to better optimization by the regex engine with the larger list of profane words. The new positions of the test words might lead to more efficient pattern matching, resulting in faster termination in some scenarios.

### How Regex Works:
1. **Regex Compilation**:
   - When a regex pattern is compiled, it creates an internal state machine that processes the input text.
   - The order of alternations (e.g., `word1|word2|word3`) can affect how quickly the regex engine finds a match.

2. **Matching Process**:
   - The regex engine scans the input text from left to right.
   - For each position in the text, it tries to match the pattern.
   - If a match is found, it can either stop (for `exists()`) or continue (for `censor()`).

### Impact of Word Positions:
1. **Early Termination**:
   - If a profane word is found early in the text, the `exists()` function can terminate early.
   - The position of words in the regex pattern can affect how quickly a match is found.

2. **Regex Optimization**:
   - Regex engines often optimize patterns by reordering alternations based on frequency or length.
   - If the test words are further down the list, which they are in the larger profane-words list, the regex engine might skip over more non-matching words before finding a match, but this doesn't necessarily mean fewer checks.

### Summary:
1. **Improved Performance for `exists() - large profane text`**:
   - **Early Termination**: If the large profane text contains many instances of the test words, the regex engine might find matches more quickly due to better optimization of the pattern.
   - **Regex Optimization**: The larger list might lead to better optimization by the regex engine, improving performance.

2. **Improved Performance for `exists() - partial match, small profane text`**:
   - **Early Termination**: For partial matches, the increased number of profane words increases the chances of finding a match sooner (unlikely in the case of v1 test-data).
   - **Regex Optimization**: The regex engine might optimize the pattern better with the larger list, leading to faster matches.
